### ISSUE TITLE
Code blocks not visible

### ISSUE THREAD

**Issue by mustafaascha** [clojuredocs/guides#277] opened 2021-11-14 18:59 UTC
Using Safari on iOS 14.8, I'm not able to see code blocks on clojure-doc.org. At the moment, I'm looking at the [Intro to Clojure](http://clojure-doc.org/articles/tutorials/introduction.html) page--there are several sections where a trailing colon refers to a code block that isn't shown. 

I haven't checked page source to see if the code blocks are missing altogether but will happily follow up on any questions

Here's a screenshot for reference ![a screenshot for reference](https://user-images.githubusercontent.com/14143556/141694516-30686e23-3378-4208-a106-52963090a47c.png)

**Comment by seancorfield** [comment] 2021-11-14 19:36
Unfortunately, the infrastructure hosting clojure-doc.org is no longer being maintained so, right now, there is no way to update the site, even if this repo has changes committed -- just setting your expectations that this will not be fixed any time soon.

**Comment by seancorfield** [comment] 2021-11-14 21:45
I'm am resurrecting this site at https://clojure-doc.github.io so feel free to recreate this issue at https://github.com/clojure-doc/clojure-doc.github.io/issues or submit a PR https://github.com/clojure-doc/clojure-doc.github.io/pulls

**Comment by mustafaascha** [comment] 2021-11-15 04:22
I'm seeing code blocks on the GitHub pages site--thank you for this!!

**Comment by seancorfield** [comment] 2021-11-15 04:31
Thanks for confirming that the issue is fixed on the new Cryogen version of the site. I'll close this out.

**Closed by seancorfield** 2021-11-15 04:31 UTC
